#!/bin/sh

set -xe

# create required dirs
mkdir -p ~/.vim/autoload ~/.vim/bundle

# install pathogen
if [ ! -f ~/.vim/autoload/pathogen.vim  ]; then
    wget -O ~/.vim/autoload/pathogen.vim 'https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim'
fi

bundle=~/.vim/bundle
gh=https://github.com

# show current directory on side
if [ ! -d $bundle/nerdtree  ]; then
    git clone $gh/scrooloose/nerdtree.git $bundle/nerdtree
fi
# kotlin syntax highlighting
if [ ! -d $bundle/kotlin-vim ]; then
    git clone $gh/udalov/kotlin-vim $bundle/kotlin-vim
fi
# auto-complete for braces etc
if [ ! -d $bundle/delimitMate ]; then
    git clone $gh/Raimondi/delimitMate $bundle/delimitMate
fi
# git awareness
if [ ! -d $bundle/vim-gitgutter ]; then
    git clone $gh/airblade/vim-gitgutter $bundle/vim-gitgutter
fi
