#!/bin/sh

set -xe

wd=`pwd`
if [ ! -f ~/.zshrc ]; then
    ln -s $wd/zshrc ~/.zshrc
fi
if [ ! -f ~/.vimrc ]; then
    ln -s $wd/vimrc ~/.vimrc
fi
if [ ! -f ~/.imwheelrc ]; then
    ln -s $wd/imwheelrc ~/.imwheelrc
fi
if [ ! -f ~/.gitignore_global ]; then
    ln -s $wd/gitignore_global ~/.gitignore_global
fi
if [ ! -d ~/.oh-my-zsh ]; then
    git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
fi
if [ ! -d ~/.tmux/plugins/tpm ]; then
    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
set +x

./setup-vim
./setup-zsh
./setup-tmux
