#!/bin/sh

set -xe

# create required dirs
mkdir -p ~/.vim/autoload ~/.vim/bundle

# install pathogen
if [ ! -f ~/.vim/autoload/pathogen.vim  ]; then
    wget -O ~/.vim/autoload/pathogen.vim 'https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim'
fi

# install nerdtree
if [ ! -d ~/.vim/bundle/nerdtree  ]; then
    git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
fi
